# Generated by Django 4.2.3 on 2023-07-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='cep',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
